export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#07090f] px-6 py-8 text-[#dde2ef]">
      <div className="mx-auto max-w-4xl">
        <a
          href="/"
          className="mb-8 inline-block rounded-lg bg-[#172036] px-4 py-2 text-sm text-[#7a9abd]"
        >
          ← Back to Home
        </a>

        <div className="rounded-2xl border border-[#172036] bg-[#0e1526] p-8">
          <h1 className="text-3xl font-extrabold">
            KwachaRise — Privacy Policy
          </h1>

          <div className="mt-4 space-y-1 text-sm text-[#7a9abd]">
            <p>
              <strong className="text-[#dde2ef]">Last updated:</strong> June
              2025
            </p>
            <p>
              <strong className="text-[#dde2ef]">Platform:</strong>{" "}
              kwacharise.com
            </p>
            <p>
              <strong className="text-[#dde2ef]">Operated by:</strong>{" "}
              KwachaRise [Company Registration Number — insert PACRA number once
              issued]
            </p>
            <p>
              <strong className="text-[#dde2ef]">
                Country of Operation:
              </strong>{" "}
              Republic of Zambia
            </p>
          </div>

          <div className="mt-8 space-y-8 leading-7 text-[#7a9abd]">
            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                1. Introduction and Legal Basis
              </h2>

              <p className="mt-3">
                KwachaRise (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is
                committed to protecting the privacy and personal data of all
                members in accordance with the laws of the Republic of Zambia.
              </p>

              <p className="mt-3">
                This Privacy Policy is prepared and maintained in compliance
                with:
              </p>

              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>
                  The Data Protection Act No. 3 of 2021, the primary data
                  protection law of Zambia
                </li>
                <li>
                  Article 17 of the Constitution of Zambia Amendment Act No. 2
                  of 2016, which guarantees every Zambian the right to privacy
                </li>
                <li>
                  The Electronic Communications and Transactions Act No. 4 of
                  2021
                </li>
                <li>The Cyber Security and Cyber Crimes Act No. 2 of 2021</li>
              </ul>

              <p className="mt-3">
                Under the Data Protection Act No. 3 of 2021, KwachaRise
                operates as a <strong className="text-[#dde2ef]">data controller</strong>,
                meaning we determine the purposes and means by which your
                personal data is collected and processed. By registering on
                KwachaRise you consent to the collection and use of your
                information as described in this policy.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                2. What Personal Data We Collect
              </h2>

              <p className="mt-3">
                In line with the data minimisation principle under the Data
                Protection Act No. 3 of 2021, we only collect information that is
                necessary for the operation of the platform.
              </p>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                2.1 Information you provide directly
              </h3>

              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>Full name as it appears on your NRC or passport</li>
                <li>Email address</li>
                <li>Phone number/mobile money number used for transactions</li>
                <li>Password, stored in encrypted, non-readable form</li>
                <li>
                  National Registration Card NRC or passport photo submitted for
                  KYC identity verification
                </li>
                <li>Payment screenshots uploaded as proof of deposit</li>
                <li>Messages submitted through the Support section</li>
              </ul>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                2.2 Information generated by your activity on the platform
              </h3>

              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>Deposit records including amounts, methods, references, and dates</li>
                <li>Withdrawal requests and pairing records</li>
                <li>Investment cycle history and tier status</li>
                <li>Referral activity and bonus records</li>
                <li>Login timestamps and session activity</li>
                <li>Notification and communication preferences</li>
                <li>Broadcast message read records</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                3. Why We Collect and Process Your Data
              </h2>

              <p className="mt-3">
                Under the Data Protection Act No. 3 of 2021, personal data must
                be collected for specific, legitimate purposes. We process your
                data for the following lawful purposes only:
              </p>

              <div className="mt-5 overflow-x-auto">
                <table className="w-full min-w-[700px] border-collapse text-left text-sm">
                  <thead>
                    <tr className="border-b border-[#172036] text-[#4e6880]">
                      <th className="py-3">Purpose</th>
                      <th className="py-3">Legal Basis</th>
                      <th className="py-3">Data Used</th>
                    </tr>
                  </thead>

                  <tbody>
                    {[
                      [
                        "Creating and managing your account",
                        "Contractual necessity",
                        "Name, email, phone, password",
                      ],
                      [
                        "Identity verification (KYC)",
                        "Legal obligation and anti-money laundering compliance",
                        "NRC or passport photo",
                      ],
                      [
                        "Processing deposits",
                        "Contractual necessity",
                        "Payment details, screenshots, mobile number",
                      ],
                      [
                        "Processing withdrawals and pairing",
                        "Contractual necessity",
                        "Name, mobile number, tier, withdrawal amount",
                      ],
                      [
                        "Sending WhatsApp and email notifications",
                        "Consent (opt-in during registration)",
                        "Phone number, email address",
                      ],
                      [
                        "Referral bonus tracking",
                        "Contractual necessity",
                        "Email, referral code activity",
                      ],
                      [
                        "Fraud prevention and platform security",
                        "Legitimate interest and legal obligation",
                        "All account and transaction data",
                      ],
                      [
                        "Compliance with Zambian law",
                        "Legal obligation",
                        "Identity and transaction records",
                      ],
                    ].map(([purpose, legalBasis, dataUsed]) => (
                      <tr key={purpose} className="border-b border-[#172036]">
                        <td className="py-3 pr-4 text-[#dde2ef]">{purpose}</td>
                        <td className="py-3 pr-4">{legalBasis}</td>
                        <td className="py-3">{dataUsed}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <p className="mt-3">
                We do not process your personal data for any purpose other than
                those listed above without obtaining your explicit consent.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                4. How We Share Your Data
              </h2>

              <p className="mt-3">
                KwachaRise does not sell, rent, or trade your personal
                information to any third party under any circumstances.
              </p>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                4.1 With other members during pairing
              </h3>

              <p className="mt-2">
                When you are matched for a withdrawal, your first name and
                registered mobile number are shared with the member who will be
                sending you payment. This sharing is strictly limited to what is
                necessary to complete the transaction. You consent to this by
                submitting a withdrawal request.
              </p>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                4.2 With platform administrators
              </h3>

              <p className="mt-2">
                Admins and the Super Admin can view member profiles, KYC
                documents, deposit records, and transaction history solely for
                the purpose of managing and operating the platform. Access is
                restricted to authorised personnel only.
              </p>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                4.3 With technology service providers
              </h3>

              <p className="mt-2">
                We use the following third party services to operate the
                platform. Each is bound by their own privacy and security
                obligations:
              </p>

              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>
                  <strong className="text-[#dde2ef]">Supabase</strong> — secure
                  cloud database storage and authentication
                </li>
                <li>
                  <strong className="text-[#dde2ef]">Resend</strong> — email
                  delivery service for notifications and password resets
                </li>
                <li>
                  <strong className="text-[#dde2ef]">Twilio</strong> — WhatsApp
                  notification delivery
                </li>
                <li>
                  <strong className="text-[#dde2ef]">Vercel</strong> — platform
                  hosting and deployment
                </li>
              </ul>

              <p className="mt-3">
                These providers are given access only to the minimum information
                necessary to perform their functions and are not permitted to use
                your data for their own purposes.
              </p>

              <h3 className="mt-5 font-bold text-[#dde2ef]">
                4.4 For legal and regulatory compliance
              </h3>

              <p className="mt-2">
                In compliance with Zambian law we may disclose member
                information to:
              </p>

              <ul className="mt-3 list-disc space-y-2 pl-6">
                <li>
                  The Financial Intelligence Centre of Zambia in cases of
                  suspected money laundering or financial crime
                </li>
                <li>
                  The Office of the Data Protection Commissioner if required
                  under the Data Protection Act No. 3 of 2021
                </li>
                <li>
                  Zambian courts or law enforcement authorities when required by
                  a valid court order or legal process
                </li>
              </ul>

              <p className="mt-3">
                We will notify you of any such disclosure where permitted by
                law.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                5. Your Rights Under the Data Protection Act No. 3 of 2021
              </h2>

              <p className="mt-3">
                The Data Protection Act No. 3 of 2021 gives you the following
                rights regarding your personal data:
              </p>

              <div className="mt-3 space-y-3">
                <p>
                  <strong className="text-[#dde2ef]">Right to Access</strong> —
                  You have the right to request a copy of the personal data we
                  hold about you at any time.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">Right to Rectification</strong>{" "}
                  — You have the right to request correction of any inaccurate
                  or incomplete personal data we hold about you.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">Right to Erasure</strong> —
                  You have the right to request deletion of your personal data.
                  This right is subject to our legal obligations to retain
                  certain records under Zambian law.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">
                    Right to Restrict Processing
                  </strong>{" "}
                  — You have the right to request that we limit how we use your
                  data in certain circumstances.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">Right to Object</strong> —
                  You have the right to object to the processing of your data
                  where it is based on legitimate interests.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">
                    Right to Withdraw Consent
                  </strong>{" "}
                  — Where processing is based on your consent, such as WhatsApp
                  notifications, you may withdraw that consent at any time
                  through your account settings. Withdrawal does not affect the
                  lawfulness of processing carried out before withdrawal.
                </p>

                <p>
                  <strong className="text-[#dde2ef]">
                    Right to Data Portability
                  </strong>{" "}
                  — You have the right to receive your personal data in a
                  structured, commonly used format.
                </p>
              </div>

              <p className="mt-3">
                To exercise any of these rights please contact us through the
                Support section on the platform. We will respond within a
                reasonable timeframe and in accordance with the Data Protection
                Act No. 3 of 2021.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                6. Data Storage, Security, and Cross-Border Transfers
              </h2>

              <div className="mt-3 space-y-3">
                <p>
                  6.1 All personal data is stored on secure cloud servers.
                  Sensitive data including KYC documents and payment screenshots
                  are stored in a private, access-controlled storage environment.
                </p>

                <p>
                  6.2 Passwords are hashed and encrypted at all times. They are
                  never stored or visible in plain text to anyone including
                  platform administrators.
                </p>

                <p>
                  6.3 We apply industry standard security measures including
                  encrypted connections HTTPS, access controls, and regular
                  security reviews to protect your data.
                </p>

                <p>
                  6.4 In accordance with the Data Protection Act No. 3 of 2021,
                  personal data may be transferred to and stored on servers
                  outside the Republic of Zambia where our service providers
                  operate, including Supabase, Vercel, Resend, and Twilio. Such
                  transfers are made only where the receiving country or
                  organisation provides adequate data protection safeguards. By
                  using KwachaRise you consent to these transfers where necessary
                  for the provision of the service.
                </p>

                <p>
                  6.5 Despite our best efforts no digital system is entirely free
                  from risk. We cannot guarantee absolute security of data
                  transmitted over the internet and members use the platform at
                  their own risk in this regard.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                7. Data Retention
              </h2>

              <div className="mt-3 space-y-3">
                <p>
                  7.1 We retain your account information and transaction records
                  for as long as your account is active and for a period of 5
                  years after account closure or expiry, in line with standard
                  financial record-keeping practice and Zambian legal
                  requirements.
                </p>

                <p>
                  7.2 KYC documents are retained for as long as required by
                  applicable Zambian anti-money laundering and identity
                  verification obligations.
                </p>

                <p>
                  7.3 Where you request deletion of your account, we will delete
                  or anonymise your personal data except where we are required by
                  law to retain certain records.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                8. Cookies and Session Technology
              </h2>

              <p className="mt-3">
                KwachaRise uses session cookies and similar technologies solely
                to maintain your login session and ensure the security and
                functionality of the platform. These technologies do not track
                your activity outside of kwacharise.com and do not collect data
                for advertising purposes.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                9. Children&apos;s Privacy
              </h2>

              <p className="mt-3">
                KwachaRise is strictly for users aged 18 years and above in
                compliance with Zambian law and our Terms and Conditions. We do
                not knowingly collect personal data from any person under the age
                of 18. If we become aware that a minor has registered on the
                platform the account will be immediately closed and all
                associated personal data deleted without delay.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                10. Data Breach Notification
              </h2>

              <p className="mt-3">
                In the event of a personal data breach that is likely to result
                in a risk to your rights and freedoms, KwachaRise will notify
                the Office of the Data Protection Commissioner of Zambia and
                affected members as required under the Data Protection Act No. 3
                of 2021. Notification will be made without undue delay and will
                include the nature of the breach, the data affected, and the
                steps being taken to address it.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                11. Future Bank Partnerships
              </h2>

              <p className="mt-3">
                KwachaRise intends to establish formal partnerships with licensed
                banking institutions in Zambia in future. When such partnerships
                are established, additional data sharing agreements and
                compliance requirements under the Banking and Financial Services
                Act No. 7 of 2017 may apply. Members will be notified of any
                material changes to this Privacy Policy before they take effect.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                12. Changes to This Policy
              </h2>

              <p className="mt-3">
                We may update this Privacy Policy from time to time to reflect
                changes in Zambian law, platform operations, or data processing
                practices. Members will be notified of significant changes
                through the in-app broadcast notification system and by email.
                The date at the top of this document will always reflect when it
                was last updated. Continued use of the platform after an updated
                policy is published constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-[#dde2ef]">
                13. Contact and Complaints
              </h2>

              <p className="mt-3">
                If you have any questions, concerns, or requests relating to
                this Privacy Policy or how your personal data is handled, please
                contact us through the Support section on the platform at
                kwacharise.com.
              </p>

              <p className="mt-3">
                If you are not satisfied with how we handle your request you
                have the right to lodge a complaint with the{" "}
                <strong className="text-[#dde2ef]">
                  Office of the Data Protection Commissioner of Zambia
                </strong>
                , which is the statutory supervisory authority established under
                the Data Protection Act No. 3 of 2021.
              </p>
            </section>

            <p className="rounded-xl border border-[#00b86b33] bg-[#00b86b0a] p-5 text-sm text-[#00b86b]">
              By creating an account on KwachaRise, you confirm that you have
              read and understood this Privacy Policy and freely consent to the
              collection, processing, and use of your personal data as described
              above, in accordance with the Data Protection Act No. 3 of 2021 of
              the Republic of Zambia.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}